# Generated by Django 3.1.2 on 2020-10-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='source',
        ),
    ]
