# Generated by Django 3.1.2 on 2020-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0002_remove_postmodel_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='note_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
