# Generated by Django 3.1.2 on 2020-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0003_postmodel_note_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='summly',
            field=models.TextField(default='', null=True),
        ),
    ]
