# Generated by Django 3.1.2 on 2020-10-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0004_postmodel_summly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='summly',
            new_name='summary',
        ),
    ]
