# Generated by Django 3.1.2 on 2020-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0005_auto_20201028_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='blog_name',
            field=models.TextField(default='', null=True),
        ),
    ]
