# Generated by Django 3.1.2 on 2020-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0006_postmodel_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='blog_url',
            field=models.TextField(default='', null=True),
        ),
    ]
