# Generated by Django 3.1.2 on 2020-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankapp', '0007_postmodel_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='source_url',
            field=models.TextField(default='', null=True),
        ),
    ]
